import { v4 as uuidv4 } from "uuid";
// https://www.hooksounds.com/
function playList() {
    return [
        {
            title: "Imperium",
            cover: "https://d1y5x10xyo8lk6.cloudfront.net/wp-content/uploads/edd/2020/11/Imperium-1658361.jpg",
            info: "An upbeat dance track with a motivational feel to it. The house beat is catchy and has a cheerful vibe to it.  A suitable choice for vibrant,  fast-paced content.",
            audio: "https://media.hksns.com/wp-content/uploads/edd/2020/11/5fb43d28bf8728.85542184/Imperium-FULL.mp3",
            genre: "Electronic",
            id: uuidv4(),
            active: true,
        },
        {
            title: "Family Day",
            cover: "https://d1y5x10xyo8lk6.cloudfront.net/wp-content/uploads/edd/2020/11/Family-Day-1658371.jpg",
            info: "A beautiful acoustic track with a heartwarming folk sound. The instrumental has an emotional aspect that gently tugs the listeners' heartstrings. A suitable choice for any gentle, family-oriented content.",
            audio: "https://media.hksns.com/wp-content/uploads/edd/2020/11/5fb441a0e17058.27601612/FamilyDay-FULL.mp3",
            genre: "Acoustic",
            id: uuidv4(),
            active: false,
        },
        {
            title: "When The Sun Rises",
            cover: "https://d1y5x10xyo8lk6.cloudfront.net/wp-content/uploads/edd/2020/11/When-The-Sun-Rises-1658425.jpg",
            info: "An elegant background instrumental with a brilliantly arranged orchestral melody. This graceful musical composition is suitable for cinematic content, Christmas content, Halloween content, and any other projects that require a festive acoustic sound.",
            audio: "https://media.hksns.com/wp-content/uploads/edd/2020/11/5fb44bf1ae6258.75276194/WhenTheSunRises-FULL.mp3",
            genre: "Cinematic",
            id: uuidv4(),
            active: false,
        },
        {
            title: "Cinematic Hip Hop",
            cover: "https://d1y5x10xyo8lk6.cloudfront.net/wp-content/uploads/edd/2020/11/Cinematic-Hip-Hop-1657328.jpg",
            info: "A calm Hip-hop track with a chilled, laid-back vibe. The melodic rhythm has an appealing quality that makes it suitable for cinematic content, web videos, ads, drone footage, online reviews, and many other multimedia projects,",
            audio: "https://media.hksns.com/wp-content/uploads/edd/2020/11/5fb31453ec1d78.36629401/CinematicHipHop-FULL.mp3",
            genre: "Hip Hop",
            id: uuidv4(),
            active: false,
        },
        {
            title: "Rescue",
            cover: "https://d1y5x10xyo8lk6.cloudfront.net/wp-content/uploads/edd/2020/11/Rescue-1653074.jpg",
            info: "A high-energy house track with catchy vocal chops and a memorable dance beat. If you're searching for a lively, trance-style dance beat, then this is it!",
            audio: "https://media.hksns.com/wp-content/uploads/edd/2020/11/5fadae238ef391.61641340/Rescue-FULL.mp3",
            genre: "Electronic",
            id: uuidv4(),
            active: false,
        },
        {
            title: "The Revolution",
            cover: "https://d1y5x10xyo8lk6.cloudfront.net/wp-content/uploads/edd/2020/11/The-Revolution-1651804.jpg",
            info: "An upbeat electronic dance track with a catchy melodious flow. A perfect background tune for lively, feel-good content.",
            audio: "https://media.hksns.com/wp-content/uploads/edd/2020/11/5fac2d47eb91e7.98585201/TheRevolution-FULL.mp3",
            genre: "Electronic",
            id: uuidv4(),
            active: false,
        },
        {
            title: "Pulsing Heart",
            cover: "https://d1y5x10xyo8lk6.cloudfront.net/wp-content/uploads/edd/2020/11/Pulsing-Heart-1651820.jpg",
            info: "A bouncy electro-pop track that features elements of Future Bass and Chilltrap. This feel-good sound is compatible with fun, cheerful, heartwarming content.",
            audio: "https://media.hksns.com/wp-content/uploads/edd/2020/11/5fac32c95e7d65.59812239/PulsingHeart-FULL.mp3",
            genre: "Electronic",
            id: uuidv4(),
            active: false,
        },
        {
            title: "Dance Forever",
            cover: "https://d1y5x10xyo8lk6.cloudfront.net/wp-content/uploads/edd/2020/11/Dance-Forever-1650617.jpg",
            info: "A powerful EDM track with a memorable dance beat. The synth effects and transitions add a dynamic effect that is ideal for a wide range of content including YouTube videos,  sports videos,  reviews, commercials/ads, summer videos, and much more.",
            audio: "https://media.hksns.com/wp-content/uploads/edd/2020/11/5faae3cf1e79f8.67598694/DanceForever-FULL.mp3",
            genre: "Electronic",
            id: uuidv4(),
            active: false,
        },
        {
            title: "Transformer",
            cover: "https://d1y5x10xyo8lk6.cloudfront.net/wp-content/uploads/edd/2020/11/Transformer-1649746.jpg",
            info: "A bass-heavy electronic track that incorporates elements of Hip-Hop, Grime, and Dubstep. This upbeat sound is perfect for uptempo, adrenaline-filled content.",
            audio: "https://media.hksns.com/wp-content/uploads/edd/2020/11/5fa986c12d34e5.82106395/Transformer-FULL.mp3",
            genre: "Electronic",
            id: uuidv4(),
            active: false,
        },
        {
            title: "Remember The Time",
            cover: "https://d1y5x10xyo8lk6.cloudfront.net/wp-content/uploads/edd/2020/11/Remember-The-Time-1649863.jpg",
            info: "Remember The TimeAn upbeat electro track with a house beat that is reminiscent of the disco era. This dance sound is ideal for bold, fun, and positive content.",
            audio: "https://media.hksns.com/wp-content/uploads/edd/2020/11/5fb4d695a85f58.07188030/RememberTheTimeFULL.mp3",
            genre: "House",
            id: uuidv4(),
            active: false,
        },
        {
            title: "Shake The Body",
            cover: "https://d1y5x10xyo8lk6.cloudfront.net/wp-content/uploads/edd/2020/11/Shake-The-Body-1647759.jpg",
            info: "A vibrant electronic track that features catchy great break-beats that give the music a universal appeal. The synth elements make it ideal for edgy, progressive content.",
            audio: "https://media.hksns.com/wp-content/uploads/edd/2020/11/5fa5d551922b81.58182399/ShakeTheBody-FULL.mp3",
            genre: "Electronic",
            id: uuidv4(),
            active: false,
        },
        {
            title: "Plenum",
            cover: "https://d1y5x10xyo8lk6.cloudfront.net/wp-content/uploads/edd/2020/11/Plenum-1646175.jpg",
            info: "A captivating cinematic track that is perfect for any project that has a dramatic or suspenseful theme.",
            audio: "https://media.hksns.com/wp-content/uploads/edd/2020/11/5fa32618506cc3.35346407/Plenum-FULL.mp3",
            genre: "Cinematic",
            id: uuidv4(),
            active: false,
        },
        {
            title: "Come Back Home",
            cover: "https://d1y5x10xyo8lk6.cloudfront.net/wp-content/uploads/edd/2020/11/Come-Back-Home-1647806.jpg",
            info: "A mellow Hip-Hop track with a melodic rhythm that includes orchestral elements. The brilliant blend of instruments and memorable beat patterns make this an ideal choice for vibrant, trendy, urban content.",
            audio: "https://media.hksns.com/wp-content/uploads/edd/2020/11/5fa5e27d3ba243.08527923/ComeBackHome-FULL.mp3",
            genre: "Hip Hop",
            id: uuidv4(),
            active: false,
        },
        {
            title: "Lonely Boy",
            cover: "https://d1y5x10xyo8lk6.cloudfront.net/wp-content/uploads/edd/2020/11/Lonely-Boy-1632291.jpg",
            info: "A captivating mid-tempo track that features elements of house, ambient electro, and synth-pop. Perfect for optimistic, feel-good content.",
            audio: "https://media.hksns.com/wp-content/uploads/edd/2020/10/5f8f324f22b1e9.36360961/LonelyBoy-FULL.mp3",
            genre: "Electronic",
            id: uuidv4(),
            active: false,
        },
        {
            title: "Cyber Friends",
            cover: "https://d1y5x10xyo8lk6.cloudfront.net/wp-content/uploads/edd/2020/11/Cyber-Friends-1628444.jpg",
            info: "A vibrant electronic dance track that is heavily influenced by the disco era. The positive, upbeat sound is perfect for, travel videos, fun tech content, vlogs, and any other dynamic projects.",
            audio: "https://media.hksns.com/wp-content/uploads/edd/2020/10/5f889034698013.22578561/CyberFriends-FULL.mp3",
            genre: "Electronic",
            id: uuidv4(),
            active: false,
        },
    ];
}

export default playList;